from pygments.lexer import RegexLexer, include, words
from pygments.token import String, Comment, Keyword, Name, Number, Text, Operator, Punctuation

class AppianLexer(RegexLexer):
    name = 'appian'
    
    keywords = words(
        (
            'false', 'true', 'null'
        ),
        suffix = r'\b',
        prefix = r'\b'
    )

    built_in_functions = words(
        (
            # Array Functions
            "a!flatten",
            "append",
            "index",
            "insert",
            "joinarray",
            "ldrop",
            "length",
            "rdrop",
            "remove",
            "reverse",
            "updatearray",
            "where",
            "wherecontains",

            # Set Functions
            "contains",
            "difference",
            "intersection",
            "symmetricdifference",
            "union",
            "bin2dec",
            "bin2hex",
            "bin2oct",
            "dec2bin",
            "dec2hex",
            "dec2oct",
            "hex2bin",
            "hex2dec",
            "hex2oct",
            "oct2bin",
            "oct2dec",
            "oct2hex",

            # Connector Functions
            "a!cmiCopyDocumentFromAppian",
            "a!cmiCopyDocumentToAppian",
            "a!cmiCopyDocumentToAppianFolder",
            "a!cmiCreateFolder",
            "a!cmiDelete",
            "a!cmiGetFolderChildren",
            "a!cmiGetObjectIdByPath",
            "a!cmiGetProperties",
            "a!cmiGetRepoInfo",
            "a!sapBapiParameters",
            "a!sapInvoke",
            "a!sapInvokeWithCommit",
            "a!sblCreate",
            "a!sblDelete",
            "a!sblInvoke",
            "a!sblInvokeWriter",
            "a!sblQuery",
            "a!sblUpdateFieldValue",
            "a!httpAuthenticationBasic",
            "a!httpFormPart",
            "a!httpHeader",
            "a!httpQueryParameter",
            "a!scsField",
            "a!wsConfig",
            "a!wsHttpCredentials",
            "a!wsHttpHeaderField",
            "a!wsUsernameToken",
            "a!wsUsernameTokenScs",

            # Conversion Functions
            "displayvalue",
            "externalize",
            "internalize",
            "toboolean",
            "tocommunity",
            "todate",
            "todatetime",
            "todecimal",
            "todocument",
            "toemailaddress",
            "toemailrecipient",
            "tofolder",
            "tointeger",
            "tointervalds",
            "toknowledgecenter",
            "tostring",
            "totime",
            "touniformstring",
            "caladddays",
            "caladdhours",
            "calisworkday",
            "calisworktime",
            "calworkdays",
            "calworkhours",
            "date",
            "datetime",
            "datevalue",
            "day",
            "dayofyear",
            "days360",
            "daysinmonth",
            "edate",
            "eomonth",
            "gmt",
            "hour",
            "intervalds",
            "isleapyear",
            "lastndays",
            "local",
            "milli",
            "minute",
            "month",
            "networkdays",
            "now",
            "second",
            "time",
            "timevalue",
            "timezone",
            "timezoneid",
            "today",
            "weekday",
            "weeknum",
            "workday",
            "year",
            "yearfrac",

            # Evaluation Functions
            "a!localVariables",
            "a!refreshVariable",
            "a!save",
            "bind",
            "load",
            "with",

            # Informational Functions
            "cast",
            "error",
            "infinity",
            "isinfinite",
            "isnegativeinfinity",
            "isnull",
            "ispositiveinfinity",
            "nan",
            "runtimetypeof",
            "typename",
            "typeof",
            "a!authorizationLink",
            "a!buttonArrayLayout",
            "a!buttonLayout",
            "a!buttonWidget",
            "a!documentDownloadLink",
            "a!dynamicLink",
            "a!linkField",
            "a!newsEntryLink",
            "a!processTaskLink",
            "a!recordActionField",
            "a!recordActionItem",
            "a!recordLink",
            "a!reportLink",
            "a!safeLink",
            "a!startProcessLink",
            "a!submitLink",
            "a!userRecordLink",
            "a!documentAndFolderBrowserFieldColumns",
            "a!documentBrowserFieldColumns",
            "a!folderBrowserFieldColumns",
            "a!groupBrowserFieldColumns",
            "a!hierarchyBrowserFieldColumns",
            "a!hierarchyBrowserFieldColumnsNode",
            "a!hierarchyBrowserFieldTree",
            "a!hierarchyBrowserFieldTreeNode",
            "a!orgChartField",
            "a!userAndGroupBrowserFieldColumns",
            "a!userBrowserFieldColumns",
            "a!barChartField",
            "a!chartReferenceLine",
            "a!chartSeries",
            "a!colorSchemeCustom",
            "a!columnChartField",
            "a!lineChartField",
            "a!pieChartField",
            "a!documentImage",
            "a!documentViewerField",
            "a!gaugeField",
            "a!gaugeFraction",
            "a!gaugeIcon",
            "a!gaugePercentage",
            "a!imageField",
            "a!milestoneField",
            "a!progressBarField",
            "a!richTextBulletedList",
            "a!richTextDisplayField",
            "a!richTextHeader",
            "a!richTextIcon",
            "a!richTextImage",
            "a!richTextItem",
            "a!richTextListItem",
            "a!richTextNumberedList",
            "a!tagField",
            "a!tagItem",
            "a!timeDisplayField",
            "a!userImage",
            "a!videoField",
            "a!webContentField",
            "a!webImage",
            "a!webVideo",
            "a!gridColumn",
            "a!gridField",
            "a!gridImageColumn",
            "a!gridLayout",
            "a!gridLayoutColumnConfig",
            "a!gridLayoutHeaderCell",
            "a!gridRowLayout",
            "a!gridSelection",
            "a!gridTextColumn",
            "a!barcodeField",
            "a!dateField",
            "a!dateTimeField",
            "a!encryptedTextField",
            "a!fileUploadField",
            "a!floatingPointField",
            "a!integerField",
            "a!paragraphField",
            "a!textField",
            "a!barOverlay",
            "a!billboardLayout",
            "a!boxLayout",
            "a!cardLayout",
            "a!columnLayout",
            "a!columnOverlay",
            "a!columnsLayout",
            "a!dashboardLayout",
            "a!formLayout",
            "a!fullOverlay",
            "a!headerContentLayout",
            "a!sectionLayout",
            "a!sideBySideItem",
            "a!sideBySideLayout",
            "a!pickerFieldCustom",
            "a!pickerFieldDocuments",
            "a!pickerFieldDocumentsAndFolders",
            "a!pickerFieldFolders",
            "a!pickerFieldGroups",
            "a!pickerFieldRecords",
            "a!pickerFieldUsers",
            "a!pickerFieldUsersAndGroups",
            "a!checkboxField",
            "a!checkboxFieldByIndex",
            "a!dropdownField",
            "a!dropdownFieldByIndex",
            "a!multipledropdownField",
            "a!multipledropdownFieldByIndex",
            "a!radioButtonField",
            "a!radioButtonFieldByIndex",

            # Logical Functions
            "and",
            "choose",
            "false",
            "if",
            "not",
            "or",
            "true",

            # Looping Functions
            "a!forEach",
            "all",
            "any",
            "apply",
            "filter",
            "merge",
            "none",
            "reduce",
            "reject",

            # Mathematical Functions
            "a!distanceBetween",
            "abs",
            "ceiling",
            "combin",
            "e",
            "enumerate",
            "even",
            "exp",
            "fact",
            "factdouble",
            "floor",
            "int",
            "ln",
            "log",
            "mod",
            "mround",
            "multinomial",
            "odd",
            "pi",
            "power",
            "product",
            "quotient",
            "rand",
            "round",
            "rounddown",
            "roundup",
            "sign",
            "sqrt",
            "sqrtpi",
            "sum",
            "sumsq",
            "trunc",

            # People Functions
            "a!groupMembers",
            "a!groupsByName",
            "a!groupsByType",
            "getdistinctusers",
            "getgroupattribute",
            "group",
            "isusermemberofgroup",
            "isusernametaken",
            "loggedInUser",
            "supervisor",
            "togroup",
            "topeople",
            "touser",
            "user",

            # Scripting Functions
            "averagetaskcompletiontimeforprocessmodel",
            "averagetasklagtimeforprocessmodel",
            "averagetaskworktimeforprocessmodel",
            "community",
            "datetext",
            "document",
            "folder",
            "isInDaylightSavingTime",
            "isNativePhone",
            "isNativeTablet",
            "knowledgecenter",
            "numontimeprocessesforprocessmodel",
            "numontimetasksforprocessmodel",
            "numoverdueprocessesforprocessmodel",
            "numoverduetasksforprocessmodel",
            "numprocessesforprocessmodelforstatus",
            "numtasksforprocessmodelforstatus",
            "offsetFromGMT",
            "property",
            "queryrecord",
            "repeat",
            "todatasubset",
            "topaginginfo",
            "torecord",
            "toxml",
            "urlforrecord",
            "urlwithparameters",
            "userdate",
            "userdatetime",
            "userdatevalue",
            "userday",
            "userdayofyear",
            "userdaysinmonth",
            "useredate",
            "usereomonth",
            "userisleapyear",
            "userlocale",
            "usermonth",
            "usertimezone",
            "userweekday",
            "userweeknum",
            "useryear",
            "webservicequery",
            "webservicewrite",
            "xpathdocument",
            "xpathsnippet",
            "a!deleteFromDataStoreEntities",
            "a!writeToDataStoreEntity",
            "a!writeToMultipleDataStoreEntities",
            "a!exportDataStoreEntityToCsv",
            "a!exportDataStoreEntityToExcel",
            "a!exportProcessReportToCsv",
            "a!exportProcessReportToExcel",
            "a!createFolder",
            "a!createKnowledgeCenter",
            "a!deleteDocument",
            "a!deleteFolder",
            "a!deleteKnowledgeCenter",
            "a!docExtractionResult",
            "a!docExtractionStatus",
            "a!editDocumentProperties",
            "a!editFolderProperties",
            "a!editKnowledgeCenterProperties",
            "a!lockDocument",
            "a!modifyFolderSecurity",
            "a!modifyKnowledgeCenterSecurity",
            "a!moveDocument",
            "a!moveFolder",
            "a!unlockDocument",
            "a!addAdminsToGroup",
            "a!addMembersToGroup",
            "a!createGroup",
            "a!createUser",
            "a!deactivateUser",
            "a!deleteGroup",
            "a!editGroup",
            "a!modifyUserSecurity",
            "a!reactivateUser",
            "a!removeGroupAdmins",
            "a!removeGroupMembers",
            "a!renameUsers",
            "a!setGroupAttributes",
            "a!updateUserProfile",
            "a!updateUserType",
            "a!cancelProcess",
            "a!completeTask",
            "a!startProcess",
            "a!startRuleTestsAll",
            "a!startRuleTestsApplications",
            "a!testRuleStatusForId",
            "a!testRunResultForId",

            # Statistical Functions
            "avedev",
            "average",
            "count",
            "frequency",
            "gcd",
            "geomean",
            "harmean",
            "lcm",
            "lookup",
            "max",
            "median",
            "min",
            "mode",
            "rank",
            "stdev",
            "stdevp",
            "var",
            "varp",

            # System Functions
            "a!applyComponents",
            "a!dataSubset",
            "a!entityData",
            "a!entityDataIdentifiers",
            "a!fromJson",
            "a!httpResponse",
            "a!iconIndicator",
            "a!iconNewsEvent",
            "a!integrationError",
            "a!jsonPath",
            "a!latestHealthCheck",
            "a!listViewItem",
            "a!pagingInfo",
            "a!query",
            "a!queryAggregation",
            "a!queryAggregationColumn",
            "a!queryColumn",
            "a!queryEntity",
            "a!queryFilter",
            "a!queryLogicalExpression",
            "a!queryProcessAnalytics",
            "a!querySelection",
            "a!recordFilterChoices",
            "a!recordFilterDateRange",
            "a!recordFilterList",
            "a!recordFilterListOption",
            "a!sentimentScore",
            "a!sortInfo",
            "a!toJson",
            "a!toRecordIdentifier",
            "a!userRecordFacets",
            "a!userRecordIdentifier",
            "a!userRecordListViewItem",

            # Text Functions
            "a!swissFranc",
            "cents",
            "char",
            "charat",
            "clean",
            "cleanwith",
            "code",
            "concat",
            "currency",
            "dollar",
            "euro",
            "exact",
            "extract",
            "extractanswers",
            "find",
            "fixed",
            "initials",
            "insertkey",
            "insertkeyval",
            "insertquestions",
            "keyval",
            "left",
            "leftb",
            "len",
            "lenb",
            "like",
            "lower",
            "mid",
            "midb",
            "padleft",
            "padright",
            "pound",
            "proper",
            "replace",
            "replaceb",
            "rept",
            "resource",
            "right",
            "search",
            "searchb",
            "soundex",
            "split",
            "strip",
            "stripHtml",
            "stripwith",
            "substitute",
            "text",
            "toHtml",
            "trim",
            "upper",
            "value",
            "yen",

            # Trigonometry Functions
            "acos",
            "acosh",
            "asin",
            "asinh",
            "atan",
            "atanh",
            "cos",
            "cosh",
            "degrees",
            "radians",
            "sin",
            "sinh",
            "tan",
            "tanh",
            "a!dashboardLayoutColumns",
            "a!dynAssociate",
            "a!dynCreate",
            "a!dynDelete",
            "a!dynDisassociate",
            "a!dynRetrieve",
            "a!dynRetrieveMultiple",
            "a!dynUpdate",
            "a!formLayoutColumns",
            "a!httpQuery",
            "a!httpWrite",
            "a!sapInvokeWriter",
            "a!sectionLayoutColumns",
            "a!sfcDelete",
            "a!sfcDescribeGlobal",
            "a!sfcDescribeSObjects",
            "a!sfcInsert",
            "a!sfcQuery",
            "a!sfcSearch",
            "a!sfcUpdate",
            "a!shpCopyDocumentFromAppian",
            "a!shpCopyDocumentToAppian",
            "a!shpInvoke",
            "a!shpInvokeWriter",
            "byReference",
            "fromHtml",
            "getprocessemail",
            "getprocessmodelemail",
            "linktocommunity",
            "linktocommunityinternal",
            "linktodocument",
            "linktodocumentinternal",
            "linktofolder",
            "linktofolderinternal",
            "linktogroup",
            "linktogroupinternal",
            "linktoknowledgecenter",
            "linktoknowledgecenterinternal",
            "linktoprocessdashboard",
            "linktoprocessdashboardinternal",
            "linktoprocessmodeldashboard",
            "linktoprocessmodeldashboardinternal",
            "linktouser",
            "linktouserinternal",
            "page",
            "todiscussionthread",
            "toforum",
            "tomessage",
            "topage",
            "toportlet",
        ),
        prefix = r'\b',
        suffix = r'\('
    )

    operators = ('+', '-', '*', '/', '^', '%', '>', '>=', '<', '<=', '=', '<>', '&')

    tokens = {
        'root': [
            (r'/\*.*?\*/', Comment.Multiline),
            (r'\.\.\.( .*)?$', Comment.Single),
            (r'rule![a-zA-Z_]+', Name.Function.Magic),
            (r'cons![a-zA-Z_]+', Name.Constant),
            (r'\'type!(\\\\|\\\'|[^\'])*\'', Keyword.Type),
            (r'M_[a-zA-Z]+', Name.Function), # MongoDB CS plugin functions
            (built_in_functions, Name.Function),
            (r'fn![a-zA-Z_]+', Name.Function),
            (keywords, Keyword.Type),
            (words(operators), Operator),
            (r'[][(),:{}\\.]', Punctuation),
            (r'"(\\\\|\\"|[^"])*"', String),
            (r'\'?\w+\'?:', Name.Attribute),
            (r'local!\w+:', Keyword.Declaration),
            (r'((local|ri|pv|fv|pp|tp)!)?[a-zA-Z_]+', Name.Variable),
            (r'\'(\\\\|\\\'|[^\'])*\'', Name.Variable),
            (r'[0-9]+', Number.Integer),
            (r'[0-9.]+', Number.Decimal),
            (r'[0-9.]+', Number.Decimal),
            (r'\s+?', Text),  # Whitespace
        ]
    }
